#!/usr/bin/env bash
# Install nginx with -y flag and configure to port 80
sudo apt-get -y update
sudo apt-get -y install nginx

#Print 'Hello world' and start the server
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
