#!/usr/bin/env bash
## Configure your Nginx server so that /redirect_me is redirecting
## to another page.

# sudo apt-get update -y
# sudo apt-get install -y nginx

# echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo chown www-data:www-data /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart

